# Generated by Django 3.1.6 on 2021-02-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OriginalObjectID', models.IntegerField()),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('Zichtbaarheid', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'abonnementen',
            },
        ),
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'personen',
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=128)),
                ('Omschrijving', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=128, null=True)),
                ('Omschrijving', models.CharField(max_length=256, null=True)),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('MutatieDatum', models.DateField(auto_now=True)),
                ('GeldigVan', models.DateField()),
                ('GeldigTot', models.DateField()),
                ('Actief', models.BooleanField()),
                ('ParentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproject', to='tijdschrijven.project')),
                ('Personen', models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Persoon')),
                ('ProjectTemplateID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tijdschrijven.projecttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='persoon',
            name='Projecten',
            field=models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Project'),
        ),
        migrations.CreateModel(
            name='GeschrevenTijd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('Datum', models.DateField()),
                ('TijdsDuur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AbonnementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.abonnement')),
            ],
            options={
                'verbose_name_plural': 'geschreven tijd',
            },
        ),
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountItem', models.SmallIntegerField(blank=True, choices=[(1, 'Dienstverband')], default=1, help_text='Acoount item')),
                ('Setting', models.IntegerField(null=True)),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('GeldigVan', models.DateField()),
                ('GeldigTot', models.DateField()),
                ('PersoonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='PersoonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.persoon'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.project'),
        ),
    ]
