# Generated by Django 3.1 on 2021-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naam', models.CharField(max_length=64)),
                ('EmailAdres', models.CharField(max_length=128)),
                ('Aanmaakdatum', models.DateField()),
                ('GeldigVan', models.DateField()),
                ('GeldigTot', models.DateField()),
                ('Wachtwoord', models.BinaryField()),
                ('rol', models.SmallIntegerField(blank=True, choices=[(1, 'Medewerker'), (2, 'Leidinggevende'), (3, 'Beheerder')], default=1, help_text='Rolomschrijving')),
            ],
        ),
    ]
