# Generated by Django 3.1 on 2021-02-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tijdschrijven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OriginalObjectID', models.IntegerField()),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('Zichtbaarheid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=128)),
                ('Omschrijving', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='persoon',
            name='MutatieDatum',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='Aanmaakdatum',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=128)),
                ('Omschrijving', models.CharField(max_length=256)),
                ('ParentID', models.IntegerField()),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('MutatieDatum', models.DateField(auto_now=True)),
                ('GeldigVan', models.DateField()),
                ('GeldigTot', models.DateField()),
                ('Actief', models.BooleanField()),
                ('Personen', models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.persoon')),
                ('ProjectTemplateID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tijdschrijven.projecttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='GeschrevenTijd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('Datum', models.DateField()),
                ('TijdsDuur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AbonnementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.abonnement')),
            ],
        ),
        migrations.CreateModel(
            name='AcoountSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountItem', models.SmallIntegerField(blank=True, choices=[(1, 'Dienstverband'), (2, 'In Dienst')], default=1, help_text='Acoount item')),
                ('AanmaakDatum', models.DateField(auto_now_add=True)),
                ('GeldigVan', models.DateField()),
                ('GeldigTot', models.DateField()),
                ('PersoonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.persoon')),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='PersoonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.persoon'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.project'),
        ),
        migrations.AddField(
            model_name='persoon',
            name='Projecten',
            field=models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Project'),
        ),
    ]
