# Generated by Django 3.1 on 2021-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijdschrijven', '0002_auto_20210207_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persoon',
            name='GeldigTot',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='GeldigVan',
        ),
        migrations.AlterField(
            model_name='acoountsetting',
            name='AccountItem',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Dienstverband')], default=1, help_text='Acoount item'),
        ),
    ]
