# Generated by Django 3.1.6 on 2021-02-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijdschrijven', '0003_auto_20210207_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcoountSetting',
            new_name='AccountSetting',
        ),
        migrations.AlterField(
            model_name='project',
            name='Personen',
            field=models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Persoon'),
        ),
    ]
