# Generated by Django 3.1.6 on 2021-02-08 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tijdschrijven', '0006_auto_20210207_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ParentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tijdschrijven.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Personen',
            field=models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Persoon'),
        ),
    ]
