# Generated by Django 3.1.6 on 2021-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijdschrijven', '0008_auto_20210208_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Omschrijving',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Personen',
            field=models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Persoon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Titel',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
