# Generated by Django 3.1.6 on 2021-02-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijdschrijven', '0009_auto_20210208_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'verbose_name_plural': 'abonnementen'},
        ),
        migrations.AlterModelOptions(
            name='geschreventijd',
            options={'verbose_name_plural': 'geschreven tijd'},
        ),
        migrations.AlterModelOptions(
            name='persoon',
            options={'verbose_name_plural': 'personen'},
        ),
        migrations.AlterField(
            model_name='project',
            name='Personen',
            field=models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Persoon'),
        ),
    ]
