# Generated by Django 3.1.6 on 2021-02-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tijdschrijven', '0010_auto_20210208_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persoon',
            name='Aanmaakdatum',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='EmailAdres',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='MutatieDatum',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='Naam',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='Wachtwoord',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='rol',
        ),
        migrations.AddField(
            model_name='persoon',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='Personen',
            field=models.ManyToManyField(through='tijdschrijven.Abonnement', to='tijdschrijven.Persoon'),
        ),
    ]
